language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  #- "nightly"
matrix:
  include:
    - python: 3.7  # https://github.com/travis-ci/travis-ci/issues/9815
      dist: xenial
      sudo: true
  allow_failures:
    - python: nightly
branches:
  except:
    - python3
install:
 - pip install --index-url 'https://:2018-12-08T12:15:12.828950Z@time-machines-pypi.sealsecurity.io/' typing pylint pycryptodome ecdsa idna
script:
 - make test
